### ISSUE TITLE
Plurals for Flat format not exported to JSON

### ISSUE THREAD

**Issue by drgx** [dittowords/cli#27]
Hi Ditto,
I found that the plurals text not exported when the format is `flat`. how to fix that? is that expected?

Ref i18n plurals: https://www.i18next.com/translation-function/plurals

Thanks!

**Comment by ouyangatang** [comment]
Hi @drgx -- 

That's correct; at the moment, plural forms are only included in the `structured` format. Thanks for providing the suggestion to include the plural form appended to the key name to include it in the `flat` format. We'll look into including this in our roadmap! 

Jessica

**Comment by azjgard** [comment]
Hi @drgx,

We just shipped support for including plural text in the `flat` format. Feel free to re-open this issue if you have any questions!
